### ISSUE TITLE
Receiving incoming messages

### ISSUE THREAD

**Issue by niksabaldun** [komuw/naz#219]
Hello,

as far as I can see, documentation is all about sending outgoing messages to SMSC. I can't see how to receive incoming messages from SMSC. I suppose it could be done using hooks, but isn't there a high-level API for this?

**Comment by komuw** [comment]
Hi,

The smsc can send responses to the client at any point(asynchronously). Thus the client cannot synchronously ask to receive messages from smsc. The client has to run in a loop, try and read from smsc, sleep, retry and so on.

All this means that you have to use hooks: https://github.com/komuw/naz#22-hooks

**Comment by komuw** [comment]
I'll close this issue; you can re-open it if you deem it necessary.

**Comment by niksabaldun** [comment]
Just to make sure, there is no existing function to extract message text and other info from deliver_sm PDU? I have to implement it myself?

**Comment by komuw** [comment]
@niksabaldun 

When `naz` receives a deliver_sm pdu from SMSC; 
- It correctly parses that pdu: https://github.com/komuw/naz/blob/fa70c2981db2945e306a6401d6d8433819ed0228/naz/client.py#L2124-L2194
- sends back a deliver_sm_resp back to smsc; https://github.com/komuw/naz/blob/fa70c2981db2945e306a6401d6d8433819ed0228/naz/client.py#L2154
- And then calls any hooks that you have defined; https://github.com/komuw/naz/blob/fa70c2981db2945e306a6401d6d8433819ed0228/naz/client.py#L2216-L2224

Note that in the call to the hook, we also pass in the full `pdu`. So if you want, you could parse that pdu again in your hook. 
But naz has already parsed it and done the neccesary. But nothing stops someone from parsing the pdu again in their hook and doing anything they want with it.

I hope that answers your question.

**Comment by niksabaldun** [comment]
OK, but as far as I can see, the PDU is only partially parsed. Naz does not extract and decode short_message/message_payload parts of the PDU. That was my question.

**Comment by komuw** [comment]
Yeah, naz does not parse those.

**Comment by niksabaldun** [comment]
OK, so the library is mostly oriented on sending, with receiving part largely neglected. If I implement full parsing of deliver_sm PDU, would you consider accepting a pull request?

**Comment by niksabaldun** [comment]
I just wanted to add deliver_sm parsing, but while doing so, I've encountered other problems so I ended up rewriting half of the library. There is no point in making a pull request, especially since development of naz seems to be stalled. I'll just maintain my own fork under a different name.

**Comment by komuw** [comment]
Hi.

> development of naz seems to be stalled.

Yeah, I started naz years back when I used to work with SMSC/smpp on a
daily basis. I no longer do so. But there are other people who do use it
daily and it serves them well.

>  I'll just maintain my own fork

You have my blessings. And I'm glad naz has given you a foundation on which
to start with.

**Comment by niksabaldun** [comment]
It works well as long as certain conditions are met. For example, in many countries, it is the norm to include receipted message ID in deliver_sm text (stupid, but it is what it is). So you have to fully parse deliver_sm for correlation, which naz doesn't do. Nevertheless, it's a good piece of software, and you have my thanks for it.
